development:
  adapter: postgresql
  encoding: unicode
  database: heartsmash_development
  pool: 5
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: heartsmash_test
  pool: 5
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: heartsmash_production
  pool: 5
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  host: localhost
